name: Auto Post football News

on:
  schedule:
    - cron: '0 */6 * * *' # Jalan setiap 6 jam
  workflow_dispatch:      # Bisa dijalankan manual (klik tombol Run)

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install Dependencies
        run: pip install -r automation/requirements.txt

      - name: Run Content Engine
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GOOGLE_INDEXING_KEY: ${{ secrets.GOOGLE_INDEXING_KEY }} 
          INDEXNOW_KEY: "b0c1cebbd6004e1a9e25605cc51b2937"
        run: python automation/main.py

      - name: Commit and Push
        run: |
          git config --global user.name "footballBot"
          git config --global user.email "bot@footballdaily.com"
          
          git add .
          
          # Cek jika ada perubahan
          if git diff --staged --quiet; then
            echo "No changes to commit. Bot sleeping."
          else
            echo "Changes detected. Committing..."
            # [skip ci] ditambahkan agar GitHub Actions tidak looping, 
            # TAPI Netlify biasanya tetap akan mendeteksi ini dan melakukan deploy.
            git commit -m "âš½ New football Update [skip ci]"
            
            # Pull dulu barangkali ada update manual dari Anda agar tidak crash
            git pull --rebase origin main
            
            # Push ke main
            git push origin main
          fi
